---
# *****************************************************************************
# .pymarkdown.yml
# *****************************************************************************

# Purpose:
# pymarkdown uses a set of rules to check source files for problems. Rules can
# be specified in a configuration file such as this one.
# Author:
# Cedric H. David, 2025-2025.


# *****************************************************************************
# Configuration
# *****************************************************************************
plugins:
  md013:
    enabled: true
    line_length: 79
    heading_line_length: 79
    code_block_line_length: 79
    strict: true


# *****************************************************************************
# End
# *****************************************************************************
