---
name: Bug Report
description: If you would like to report a bug in RAPID.
title: "[bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make a suggestion for RAPID!
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I did [...] action, I noticed [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
      placeholder: I expected [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducible steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment information
      description: Include relevant environment details where the bug occurred.
      placeholder: |
        - Version of RAPID: [e.g. v1.2.3]
        - Operating System: [e.g. MacOS 12.4, Windows 11, Ubuntu 22.04]
        - Additional context: [Any other relevant environment information]
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Let us ensure open source development is sustainable!
      description: |
        We care about open source, and we would like for our interactions to be
        a productive collaboration.
      options:
        - label: |
            I have looked at previous GitHub issues and this bug has not
            yet been reported.
          required: true
        - label: |
            I have read [`CODE_OF_COLLAB.md`][COLLAB] and agree to the terms.
          required: true
        - label: |
            I understand from [`CONTRIBUTING.md`][CONTRI] that a response or
            resolution to my request is not guaranteed.
          required: true
  - type: markdown
    attributes:
      value: |
        [COLLAB]: https://github.com/c-h-david/rapid2/blob/main/CODE_OF_COLLAB.md
        [CONTRI]: https://github.com/c-h-david/rapid2/blob/main/CONTRIBUTING.md
