---
name: Proposed Enhancement
description: If you would like to suggest an enhancement to RAPID.
title: "[enhancement]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make a suggestion for RAPID!
  - type: textarea
    attributes:
      label: What would you like to suggest?
      description: |
        We cannot promise anything, but we love suggestions for improvement.
      placeholder: Please tell us.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Let us ensure open source development is sustainable!
      description: |
        We care about open source, and we would like for our interactions to be
        a productive collaboration.
      options:
        - label: |
            I have looked at previous GitHub issues and this enhancement has
            not yet been proposed.
          required: true
        - label: |
            I have read [`CODE_OF_COLLAB.md`][COLLAB] and agree to the terms.
          required: true
        - label: |
            I understand from [`CONTRIBUTING.md`][CONTRI] that a response or
            resolution to my request is not guaranteed.
          required: true
  - type: markdown
    attributes:
      value: |
      [COLLAB]: https://github.com/c-h-david/rapid2/blob/main/CODE_OF_COLLAB.md
      [CONTRI]: https://github.com/c-h-david/rapid2/blob/main/CONTRIBUTING.md
